# DataFrames.jl 介紹 (二): Joins 與 Split-Apply-Combine Strategy

## Day 018 作業1：The Split-Apply-Combine Strategy

同 Day 017，請載入 2020/4/2 COVID-19 Daily Report 資料集，計算每個國家/地區的累計確診人數，並列出所有資料筆數。

In [1]:
using DataFrames, CSV

In [2]:
df = CSV.read("04-02-2020.csv")

2569×12 DataFrame. Omitted printing of 8 columns
│ Row  │ FIPS    │ Admin2     │ Province_State │ Country_Region       │
│      │ Int64⍰  │ String⍰    │ String⍰        │ String               │
├──────┼─────────┼────────────┼────────────────┼──────────────────────┤
│ 1    │ 45001   │ Abbeville  │ South Carolina │ US                   │
│ 2    │ 22001   │ Acadia     │ Louisiana      │ US                   │
│ 3    │ 51001   │ Accomack   │ Virginia       │ US                   │
│ 4    │ 16001   │ Ada        │ Idaho          │ US                   │
│ 5    │ 19001   │ Adair      │ Iowa           │ US                   │
│ 6    │ 29001   │ Adair      │ Missouri       │ US                   │
│ 7    │ 40001   │ Adair      │ Oklahoma       │ US                   │
│ 8    │ 8001    │ Adams      │ Colorado       │ US                   │
│ 9    │ 16003   │ Adams      │ Idaho          │ US                   │
│ 10   │ 17001   │ Adams      │ Illinois       │ US                   │
⋮
│ 2559 │ missing │ missing    │ missing        │ Ukraine              │
│ 2560 │ missing │ missing    │ missing        │ United Arab Emirates │
│ 2561 │ missing │ missing    │ missing        │ United Kingdom       │
│ 2562 │ missing │ missing    │ missing        │ Uruguay              │
│ 2563 │ missing │ missing    │ missing        │ Uzbekistan           │
│ 2564 │ missing │ missing    │ missing        │ Venezuela            │
│ 2565 │ missing │ missing    │ missing        │ Vietnam              │
│ 2566 │ missing │ missing    │ missing        │ West Bank and Gaza   │
│ 2567 │ missing │ missing    │ missing        │ Zambia               │
│ 2568 │ missing │ missing    │ missing        │ Zimbabwe             │
│ 2569 │ missing │ unassigned │ Wyoming        │ US                   │

計算每個國家/地區的累計確診人數

【提示】可使用 groupby 相關的函式

In [4]:
show(df; allcols=true)

2569×12 DataFrame
│ Row  │ FIPS    │ Admin2     │ Province_State │ Country_Region       │
│      │ Int64⍰  │ String⍰    │ String⍰        │ String               │
├──────┼─────────┼────────────┼────────────────┼──────────────────────┤
│ 1    │ 45001   │ Abbeville  │ South Carolina │ US                   │
│ 2    │ 22001   │ Acadia     │ Louisiana      │ US                   │
│ 3    │ 51001   │ Accomack   │ Virginia       │ US                   │
│ 4    │ 16001   │ Ada        │ Idaho          │ US                   │
│ 5    │ 19001   │ Adair      │ Iowa           │ US                   │
│ 6    │ 29001   │ Adair      │ Missouri       │ US                   │
│ 7    │ 40001   │ Adair      │ Oklahoma       │ US                   │
│ 8    │ 8001    │ Adams      │ Colorado       │ US                   │
│ 9    │ 16003   │ Adams      │ Idaho          │ US                   │
│ 10   │ 17001   │ Adams      │ Illinois       │ US                   │
⋮
│ 2559 │ missing │ missing    │ missing        │ Ukraine              │
│ 2560 │ missing │ missing    │ missing        │ United Arab Emirates │
│ 2561 │ missing │ missing    │ missing        │ United Kingdom       │
│ 2562 │ missing │ missing    │ missing        │ Uruguay              │
│ 2563 │ missing │ missing    │ missing        │ Uzbekistan           │
│ 2564 │ missing │ missing    │ missing        │ Venezuela            │
│ 2565 │ missing │ missing    │ missing        │ Vietnam              │
│ 2566 │ missing │ missing    │ missing        │ West Bank and Gaza   │
│ 2567 │ missing │ missing    │ missing        │ Zambia               │
│ 2568 │ missing │ missing    │ missing        │ Zimbabwe             │
│ 2569 │ missing │ unassigned │ Wyoming        │ US                   │

│ Row  │ Last_Update         │ Lat      │ Long_    │ Confirmed │ Deaths │
│      │ String              │ Float64⍰ │ Float64⍰ │ Int64     │ Int64  │
├──────┼─────────────────────┼──────────┼──────────┼───────────┼────────┤
│ 1    │ 2020-04-02 23:25:27 │ 34.2233  │ -82.4617 │ 6         │ 0      │
│ 2    │ 2020-04-02 23:25:27 │ 30.2951  │ -92.4142 │ 61        │ 1      │
│ 3    │ 2020-04-02 23:25:27 │ 37.7671  │ -75.6323 │ 10        │ 0      │
│ 4    │ 2020-04-02 23:25:27 │ 43.4527  │ -116.242 │ 312       │ 3      │
│ 5    │ 2020-04-02 23:25:27 │ 41.3308  │ -94.4711 │ 1         │ 0      │
│ 6    │ 2020-04-02 23:25:27 │ 40.1906  │ -92.6008 │ 6         │ 0      │
│ 7    │ 2020-04-02 23:25:27 │ 35.8849  │ -94.6586 │ 9         │ 0      │
│ 8    │ 2020-04-02 23:25:27 │ 39.8743  │ -104.336 │ 212       │ 2      │
│ 9    │ 2020-04-02 23:25:27 │ 44.8933  │ -116.455 │ 1         │ 0      │
│ 10   │ 2020-04-02 23:25:27 │ 39.9882  │ -91.1879 │ 2         │ 0      │
⋮
│ 2559 │ 2020-04-02 23:25:14 │ 48.3794  │ 31.1656  │ 897       │ 22     │
│ 2560 │ 2020-04-02 23:25:14 │ 23.4241  │ 53.8478  │ 1024      │ 8      │
│ 2561 │ 2020-04-02 23:25:14 │ 55.3781  │ -3.436   │ 33718     │ 2921   │
│ 2562 │ 2020-04-02 23:25:14 │ -32.5228 │ -55.7658 │ 350       │ 4      │
│ 2563 │ 2020-04-02 23:25:14 │ 41.3775  │ 64.5853  │ 205       │ 2      │
│ 2564 │ 2020-04-02 23:25:14 │ 6.4238   │ -66.5897 │ 146       │ 5      │
│ 2565 │ 2020-04-02 23:25:14 │ 14.0583  │ 108.277  │ 233       │ 0      │
│ 2566 │ 2020-04-02 23:25:14 │ 31.9522  │ 35.2332  │ 161       │ 1      │
│ 2567 │ 2020-04-02 23:25:14 │ -13.1339 │ 27.8493  │ 39        │ 1      │
│ 2568 │ 2020-04-02 23:25:14 │ -19.0154 │ 29.1549  │ 9         │ 1      │
│ 2569 │ 2020-04-02 23:25:27 │ missing  │ missing  │ 0         │ 0      │

│ Row  │ Recovered │ Active │ Combined_Key                  │
│      │ Int64     │ Int64  │ String                        │
├──────┼───────────┼────────┼───────────────────────────────┤
│ 1    │ 0         │ 0      │ Abbeville, South Carolina, US │
│ 2    │ 0         │ 0      │ Acadia, Louisiana, US         │
│ 3    │ 0         │ 0      │ Accomack, Virginia, US        │
│ 4    │ 0         │ 0      │ Ada, Idaho, US                │
│ 5    │ 0         │ 0      │ Adair, Iowa, US               │
│ 6    │ 0         │ 0      │ Adair, Missouri, US           │
│ 7    │ 0         │ 0      │ Adair, Oklahoma, US           │
│ 8    │ 0         │ 0      │ Adams, Colorado, US           │
│ 9    │ 0         │ 0      │ Adams,Idaho,US                │
│ 10   │ 0         │ 0      │ Adams, Illinois, US           │
⋮
│ 2559 │ 19        │ 856    │ Ukraine                       │
│ 2560 │ 96        │ 920    │ United Arab Emirates          │
│ 2561 │ 135       │ 30662  │ United Kingdom                │
│ 2562 │ 62        │ 284    │ Uruguay                       │
│ 2563 │ 25        │ 178    │ Uzbekistan                    │
│ 2564 │ 43        │ 98     │ Venezuela                     │
│ 2565 │ 75        │ 158    │ Vietnam                       │
│ 2566 │ 18        │ 142    │ West Bank and Gaza            │
│ 2567 │ 0         │ 38     │ Zambia                        │
│ 2568 │ 0         │ 8      │ Zimbabwe                      │
│ 2569 │ 0         │ 0      │ unassigned, Wyoming, US       │

In [8]:
df2 = sort(by(df, :Country_Region, :Confirmed => sum), :Confirmed_sum, rev=true)

181×2 DataFrame
│ Row │ Country_Region                   │ Confirmed_sum │
│     │ String                           │ Int64         │
├─────┼──────────────────────────────────┼───────────────┤
│ 1   │ US                               │ 243453        │
│ 2   │ Italy                            │ 115242        │
│ 3   │ Spain                            │ 112065        │
│ 4   │ Germany                          │ 84794         │
│ 5   │ China                            │ 82432         │
│ 6   │ France                           │ 59929         │
│ 7   │ Iran                             │ 50468         │
│ 8   │ United Kingdom                   │ 34173         │
│ 9   │ Switzerland                      │ 18827         │
│ 10  │ Turkey                           │ 18135         │
⋮
│ 171 │ Somalia                          │ 5             │
│ 172 │ Botswana                         │ 4             │
│ 173 │ Gambia                           │ 4             │
│ 174 │ Belize                           │ 3             │
│ 175 │ Burundi                          │ 3             │
│ 176 │ Central African Republic         │ 3             │
│ 177 │ Malawi                           │ 3             │
│ 178 │ Saint Vincent and the Grenadines │ 2             │
│ 179 │ Sierra Leone                     │ 2             │
│ 180 │ Papua New Guinea                 │ 1             │
│ 181 │ Timor-Leste                      │ 1             │

In [10]:
# 顯示所有資料
show(df2, allrows=true, allcols=true)

181×2 DataFrame
│ Row │ Country_Region                   │ Confirmed_sum │
│     │ String                           │ Int64         │
├─────┼──────────────────────────────────┼───────────────┤
│ 1   │ US                               │ 243453        │
│ 2   │ Italy                            │ 115242        │
│ 3   │ Spain                            │ 112065        │
│ 4   │ Germany                          │ 84794         │
│ 5   │ China                            │ 82432         │
│ 6   │ France                           │ 59929         │
│ 7   │ Iran                             │ 50468         │
│ 8   │ United Kingdom                   │ 34173         │
│ 9   │ Switzerland                      │ 18827         │
│ 10  │ Turkey                           │ 18135         │
│ 11  │ Belgium                          │ 15348         │
│ 12  │ Netherlands                      │ 14788         │
│ 13  │ Canada                           │ 11284         │
│ 14  │ Austria                          │ 11129         │
│ 15  │ Korea, South                     │ 9976          │
│ 16  │ Portugal                         │ 9034          │
│ 17  │ Brazil                           │ 8044          │
│ 18  │ Israel                           │ 6857          │
│ 19  │ Sweden                           │ 5568          │
│ 20  │ Norway                           │ 5147          │
│ 21  │ Australia                        │ 5116          │
│ 22  │ Czechia                          │ 3858          │
│ 23  │ Ireland                          │ 3849          │
│ 24  │ Denmark                          │ 3573          │
│ 25  │ Russia                           │ 3548          │
│ 26  │ Chile                            │ 3404          │
│ 27  │ Ecuador                          │ 3163          │
│ 28  │ Malaysia                         │ 3116          │
│ 29  │ Poland                           │ 2946          │
│ 30  │ Romania                          │ 2738          │
│ 31  │ Philippines                      │ 2633          │
│ 32  │ India                            │ 2543          │
│ 33  │ Japan                            │ 2495          │
│ 34  │ Luxembourg                       │ 2487          │
│ 35  │ Pakistan                         │ 2421          │
│ 36  │ Saudi Arabia                     │ 1885          │
│ 37  │ Thailand                         │ 1875          │
│ 38  │ Indonesia                        │ 1790          │
│ 39  │ Greece                           │ 1544          │
│ 40  │ Finland                          │ 1518          │
│ 41  │ South Africa                     │ 1462          │
│ 42  │ Peru                             │ 1414          │
│ 43  │ Dominican Republic               │ 1380          │
│ 44  │ Mexico                           │ 1378          │
│ 45  │ Iceland                          │ 1319          │
│ 46  │ Panama                           │ 1317          │
│ 47  │ Serbia                           │ 1171          │
│ 48  │ Colombia                         │ 1161          │
│ 49  │ Argentina                        │ 1133          │
│ 50  │ Singapore                        │ 1049          │
│ 51  │ United Arab Emirates             │ 1024          │
│ 52  │ Croatia                          │ 1011          │
│ 53  │ Algeria                          │ 986           │
│ 54  │ Qatar                            │ 949           │
│ 55  │ Slovenia                         │ 897           │
│ 56  │ Ukraine                          │ 897           │
│ 57  │ Egypt                            │ 865           │
│ 58  │ Estonia                          │ 858           │
│ 59  │ New Zealand                      │ 797           │
│ 60  │ Iraq                             │ 772           │
│ 61  │ Diamond Princess                 │ 712           │
│ 62  │ Morocco                          │ 708           │
│ 63  │ Armenia                          │ 663           │
│ 64  │ Lithuania                        │ 649           │
│ 65  │ Bahrain                          │ 643           │
│ 66  │ Hungary                          │ 585           │
│ 67  │ Bosnia and Herzegovina           │ 533           │
│ 68  │ Moldova                          │ 505           │
│ 69  │ Lebanon                          │ 494           │
│ 70  │ Latvia                           │ 458           │
│ 71  │ Bulgaria                         │ 457           │
│ 72  │ Tunisia                          │ 455           │
│ 73  │ Kazakhstan                       │ 435           │
│ 74  │ Andorra                          │ 428           │
│ 75  │ Slovakia                         │ 426           │
│ 76  │ Azerbaijan                       │ 400           │
│ 77  │ Costa Rica                       │ 396           │
│ 78  │ North Macedonia                  │ 384           │
│ 79  │ Cyprus                           │ 356           │
│ 80  │ Uruguay                          │ 350           │
│ 81  │ Kuwait                           │ 342           │
│ 82  │ Taiwan*                          │ 339           │
│ 83  │ Cameroon                         │ 306           │
│ 84  │ Belarus                          │ 304           │
│ 85  │ Jordan                           │ 299           │
│ 86  │ Burkina Faso                     │ 288           │
│ 87  │ Albania                          │ 277           │
│ 88  │ Afghanistan                      │ 273           │
│ 89  │ San Marino                       │ 245           │
│ 90  │ Cuba                             │ 233           │
│ 91  │ Vietnam                          │ 233           │
│ 92  │ Oman                             │ 231           │
│ 93  │ Honduras                         │ 219           │
│ 94  │ Uzbekistan                       │ 205           │
│ 95  │ Ghana                            │ 204           │
│ 96  │ Malta                            │ 196           │
│ 97  │ Senegal                          │ 195           │
│ 98  │ Cote d'Ivoire                    │ 194           │
│ 99  │ Nigeria                          │ 184           │
│ 100 │ Mauritius                        │ 169           │
│ 101 │ West Bank and Gaza               │ 161           │
│ 102 │ Sri Lanka                        │ 151           │
│ 103 │ Venezuela                        │ 146           │
│ 104 │ Montenegro                       │ 144           │
│ 105 │ Congo (Kinshasa)                 │ 134           │
│ 106 │ Georgia                          │ 134           │
│ 107 │ Brunei                           │ 133           │
│ 108 │ Kosovo                           │ 125           │
│ 109 │ Bolivia                          │ 123           │
│ 110 │ Kyrgyzstan                       │ 116           │
│ 111 │ Cambodia                         │ 110           │
│ 112 │ Kenya                            │ 110           │
│ 113 │ Niger                            │ 98            │
│ 114 │ Trinidad and Tobago              │ 94            │
│ 115 │ Rwanda                           │ 84            │
│ 116 │ Paraguay                         │ 77            │
│ 117 │ Liechtenstein                    │ 75            │
│ 118 │ Monaco                           │ 60            │
│ 119 │ Madagascar                       │ 59            │
│ 120 │ Bangladesh                       │ 56            │
│ 121 │ Guinea                           │ 52            │
│ 122 │ Guatemala                        │ 47            │
│ 123 │ Jamaica                          │ 47            │
│ 124 │ Barbados                         │ 46            │
│ 125 │ Uganda                           │ 45            │
│ 126 │ El Salvador                      │ 41            │
│ 127 │ Djibouti                         │ 40            │
│ 128 │ Togo                             │ 39            │
│ 129 │ Zambia                           │ 39            │
│ 130 │ Mali                             │ 36            │
│ 131 │ Ethiopia                         │ 29            │
│ 132 │ Bahamas                          │ 24            │
│ 133 │ Congo (Brazzaville)              │ 22            │
│ 134 │ Eritrea                          │ 22            │
│ 135 │ Gabon                            │ 21            │
│ 136 │ Burma                            │ 20            │
│ 137 │ Tanzania                         │ 20            │
│ 138 │ Guyana                           │ 19            │
│ 139 │ Maldives                         │ 19            │
│ 140 │ Haiti                            │ 16            │
│ 141 │ Syria                            │ 16            │
│ 142 │ Equatorial Guinea                │ 15            │
│ 143 │ Mongolia                         │ 14            │
│ 144 │ Namibia                          │ 14            │
│ 145 │ Benin                            │ 13            │
│ 146 │ Saint Lucia                      │ 13            │
│ 147 │ Dominica                         │ 12            │
│ 148 │ Libya                            │ 11            │
│ 149 │ Grenada                          │ 10            │
│ 150 │ Laos                             │ 10            │

│ 151 │ Mozambique                       │ 10            │
│ 152 │ Seychelles                       │ 10            │
│ 153 │ Suriname                         │ 10            │
│ 154 │ Antigua and Barbuda              │ 9             │
│ 155 │ Eswatini                         │ 9             │
│ 156 │ Guinea-Bissau                    │ 9             │
│ 157 │ MS Zaandam                       │ 9             │
│ 158 │ Saint Kitts and Nevis            │ 9             │
│ 159 │ Zimbabwe                         │ 9             │
│ 160 │ Angola                           │ 8             │
│ 161 │ Chad                             │ 8             │
│ 162 │ Sudan                            │ 8             │
│ 163 │ Fiji                             │ 7             │
│ 164 │ Holy See                         │ 7             │
│ 165 │ Cabo Verde                       │ 6             │
│ 166 │ Liberia                          │ 6             │
│ 167 │ Mauritania                       │ 6             │
│ 168 │ Nepal                            │ 6             │
│ 169 │ Bhutan                           │ 5             │
│ 170 │ Nicaragua                        │ 5             │
│ 171 │ Somalia                          │ 5             │
│ 172 │ Botswana                         │ 4             │
│ 173 │ Gambia                           │ 4             │
│ 174 │ Belize                           │ 3             │
│ 175 │ Burundi                          │ 3             │
│ 176 │ Central African Republic         │ 3             │
│ 177 │ Malawi                           │ 3             │
│ 178 │ Saint Vincent and the Grenadines │ 2             │
│ 179 │ Sierra Leone                     │ 2             │
│ 180 │ Papua New Guinea                 │ 1             │
│ 181 │ Timor-Leste                      │ 1             │

## 作業2：請列出美國各區域或事件 (依 Province_State 欄) 的累積確診、死亡、康復人數。

【提示】使用 Split-Apply-Combine Strategy 時，有幾種不同的函式可以使用，請參照 `DataFrames.jl` 官方文件 [https://juliadata.github.io/DataFrames.jl/stable/lib/functions/#DataFrames.groupby](https://juliadata.github.io/DataFrames.jl/stable/lib/functions/#DataFrames.groupby)

In [32]:
df_US_groupby_Province_State = groupby(df[df.Country_Region .== "US", :], :Province_State)

GroupedDataFrame with 58 groups based on key: Province_State
First Group (46 rows): Province_State = "South Carolina". Omitted printing of 8 columns
│ Row │ FIPS   │ Admin2       │ Province_State │ Country_Region │
│     │ Int64⍰ │ String⍰      │ String⍰        │ String         │
├─────┼────────┼──────────────┼────────────────┼────────────────┤
│ 1   │ 45001  │ Abbeville    │ South Carolina │ US             │
│ 2   │ 45003  │ Aiken        │ South Carolina │ US             │
│ 3   │ 45005  │ Allendale    │ South Carolina │ US             │
│ 4   │ 45007  │ Anderson     │ South Carolina │ US             │
│ 5   │ 45009  │ Bamberg      │ South Carolina │ US             │
│ 6   │ 45011  │ Barnwell     │ South Carolina │ US             │
│ 7   │ 45013  │ Beaufort     │ South Carolina │ US             │
│ 8   │ 45015  │ Berkeley     │ South Carolina │ US             │
│ 9   │ 45017  │ Calhoun      │ South Carolina │ US             │
│ 10  │ 45019  │ Charleston   │ South Carolina │ US             │
⋮
│ 36  │ 45071  │ Newberry     │ South Carolina │ US             │
│ 37  │ 45073  │ Oconee       │ South Carolina │ US             │
│ 38  │ 45075  │ Orangeburg   │ South Carolina │ US             │
│ 39  │ 45077  │ Pickens      │ South Carolina │ US             │
│ 40  │ 45079  │ Richland     │ South Carolina │ US             │
│ 41  │ 45081  │ Saluda       │ South Carolina │ US             │
│ 42  │ 45083  │ Spartanburg  │ South Carolina │ US             │
│ 43  │ 45085  │ Sumter       │ South Carolina │ US             │
│ 44  │ 45087  │ Union        │ South Carolina │ US             │
│ 45  │ 45089  │ Williamsburg │ South Carolina │ US             │
│ 46  │ 45091  │ York         │ South Carolina │ US             │
⋮
Last Group (1 row): Province_State = "Virgin Islands". Omitted printing of 8 columns
│ Row │ FIPS   │ Admin2  │ Province_State │ Country_Region │
│     │ Int64⍰ │ String⍰ │ String⍰        │ String         │
├─────┼────────┼─────────┼────────────────┼────────────────┤
│ 1   │ 78     │ missing │ Virgin Islands │ US             │

In [41]:
df_final = sort(
    combine(df_US_groupby_Province_State, :Confirmed => sum, :Deaths => sum, :Recovered => sum),
    :Confirmed_sum, rev=true
)

58×4 DataFrame
│ Row │ Province_State           │ Confirmed_sum │ Deaths_sum │ Recovered_sum │
│     │ Union{Missing, String}   │ Int64         │ Int64      │ Int64         │
├─────┼──────────────────────────┼───────────────┼────────────┼───────────────┤
│ 1   │ New York                 │ 92506         │ 2373       │ 0             │
│ 2   │ New Jersey               │ 25590         │ 537        │ 0             │
│ 3   │ Michigan                 │ 10791         │ 417        │ 0             │
│ 4   │ California               │ 10773         │ 238        │ 0             │
│ 5   │ Louisiana                │ 9159          │ 310        │ 0             │
│ 6   │ Florida                  │ 9008          │ 164        │ 0             │
│ 7   │ Massachusetts            │ 8966          │ 154        │ 0             │
│ 8   │ Illinois                 │ 7695          │ 163        │ 0             │
│ 9   │ Pennsylvania             │ 7268          │ 90         │ 0             │
│ 10  │ Washington               │ 6389          │ 271        │ 0             │
⋮
│ 48  │ West Virginia            │ 216           │ 2          │ 0             │
│ 49  │ South Dakota             │ 165           │ 2          │ 0             │
│ 50  │ North Dakota             │ 159           │ 3          │ 0             │
│ 51  │ Wyoming                  │ 150           │ 0          │ 0             │
│ 52  │ Alaska                   │ 143           │ 3          │ 0             │
│ 53  │ Grand Princess           │ 103           │ 3          │ 0             │
│ 54  │ Guam                     │ 82            │ 3          │ 0             │
│ 55  │ Diamond Princess         │ 49            │ 0          │ 0             │
│ 56  │ Virgin Islands           │ 30            │ 0          │ 0             │
│ 57  │ Northern Mariana Islands │ 6             │ 1          │ 0             │
│ 58  │ Recovered                │ 0             │ 0          │ 9001          │

In [42]:
show(df_final, allrows=true)

58×4 DataFrame
│ Row │ Province_State           │ Confirmed_sum │ Deaths_sum │ Recovered_sum │
│     │ Union{Missing, String}   │ Int64         │ Int64      │ Int64         │
├─────┼──────────────────────────┼───────────────┼────────────┼───────────────┤
│ 1   │ New York                 │ 92506         │ 2373       │ 0             │
│ 2   │ New Jersey               │ 25590         │ 537        │ 0             │
│ 3   │ Michigan                 │ 10791         │ 417        │ 0             │
│ 4   │ California               │ 10773         │ 238        │ 0             │
│ 5   │ Louisiana                │ 9159          │ 310        │ 0             │
│ 6   │ Florida                  │ 9008          │ 164        │ 0             │
│ 7   │ Massachusetts            │ 8966          │ 154        │ 0             │
│ 8   │ Illinois                 │ 7695          │ 163        │ 0             │
│ 9   │ Pennsylvania             │ 7268          │ 90         │ 0             │
│ 10  │ Washington               │ 6389          │ 271        │ 0             │
│ 11  │ Georgia                  │ 5348          │ 163        │ 0             │
│ 12  │ Texas                    │ 5069          │ 77         │ 0             │
│ 13  │ Connecticut              │ 3824          │ 112        │ 0             │
│ 14  │ Colorado                 │ 3342          │ 80         │ 0             │
│ 15  │ Indiana                  │ 3038          │ 78         │ 0             │
│ 16  │ Ohio                     │ 2901          │ 81         │ 0             │
│ 17  │ Tennessee                │ 2845          │ 36         │ 0             │
│ 18  │ Maryland                 │ 2331          │ 36         │ 0             │
│ 19  │ North Carolina           │ 1977          │ 21         │ 0             │
│ 20  │ Missouri                 │ 1857          │ 22         │ 0             │
│ 21  │ Wisconsin                │ 1748          │ 38         │ 0             │
│ 22  │ Arizona                  │ 1715          │ 32         │ 0             │
│ 23  │ Virginia                 │ 1706          │ 41         │ 0             │
│ 24  │ South Carolina           │ 1554          │ 31         │ 0             │
│ 25  │ Nevada                   │ 1463          │ 38         │ 0             │
│ 26  │ Alabama                  │ 1233          │ 32         │ 0             │
│ 27  │ Mississippi              │ 1177          │ 26         │ 0             │
│ 28  │ Utah                     │ 1092          │ 7          │ 0             │
│ 29  │ Oklahoma                 │ 881           │ 34         │ 0             │
│ 30  │ Oregon                   │ 826           │ 21         │ 0             │
│ 31  │ Idaho                    │ 776           │ 9          │ 0             │
│ 32  │ Kentucky                 │ 770           │ 31         │ 0             │
│ 33  │ Minnesota                │ 742           │ 18         │ 0             │
│ 34  │ Rhode Island             │ 657           │ 12         │ 0             │
│ 35  │ District of Columbia     │ 653           │ 12         │ 0             │
│ 36  │ Arkansas                 │ 643           │ 12         │ 0             │
│ 37  │ Iowa                     │ 614           │ 11         │ 0             │
│ 38  │ Kansas                   │ 553           │ 12         │ 0             │
│ 39  │ Delaware                 │ 393           │ 12         │ 0             │
│ 40  │ New Mexico               │ 388           │ 6          │ 0             │
│ 41  │ Maine                    │ 376           │ 7          │ 0             │
│ 42  │ Vermont                  │ 338           │ 17         │ 0             │
│ 43  │ New Hampshire            │ 316           │ 3          │ 0             │
│ 44  │ Puerto Rico              │ 316           │ 12         │ 0             │
│ 45  │ Hawaii                   │ 256           │ 1          │ 0             │
│ 46  │ Nebraska                 │ 246           │ 5          │ 0             │
│ 47  │ Montana                  │ 241           │ 6          │ 0             │
│ 48  │ West Virginia            │ 216           │ 2          │ 0             │
│ 49  │ South Dakota             │ 165           │ 2          │ 0             │
│ 50  │ North Dakota             │ 159           │ 3          │ 0             │
│ 51  │ Wyoming                  │ 150           │ 0          │ 0             │
│ 52  │ Alaska                   │ 143           │ 3          │ 0             │
│ 53  │ Grand Princess           │ 103           │ 3          │ 0             │
│ 54  │ Guam                     │ 82            │ 3          │ 0             │
│ 55  │ Diamond Princess         │ 49            │ 0          │ 0             │
│ 56  │ Virgin Islands           │ 30            │ 0          │ 0             │
│ 57  │ Northern Mariana Islands │ 6             │ 1          │ 0             │
│ 58  │ Recovered                │ 0             │ 0          │ 9001          │